### ISSUE TITLE
高度以假乱真、不会被发现字迹和自己不一样的应用建议

### ISSUE THREAD

**Issue by jackatlascn** [zhaoruheng/Word-Macro#4]
如果仅仅是为了应付简单的检查，随便用一款手写字体即可，如果需要模仿自己的字迹，我的经验可能有点用处。
1.寻找大量手写字体，我找了100多款。全部安装
2.下载安装【字由】这个软件，这个软件可以输入一排字，比较不同字体呈现的效果。当然这个软件的付费功能也可以帮你寻找合适的字体。我比较习惯行楷。正楷和行草属实没法用。
3.人工找合适自己的字体，记下名字。

你以为这就结束了吗？这远没有结束。手写字体五花八门，有的是钢笔，有的是粗水笔，还要进一步挑选。
4.在Excel里输入一排示范字体，最好是一句完整的话，然后每一行用不同字体，字号18-20号，确定一下哪个字号适合自己。
5.字号确定后，再试一遍打印效果，确定一下哪个字体的打印效果跟你手写的粗细差不多。
6.大概率，你会发现全都不合适。这里有我的血泪经验分享一下，找一下打印机设置，有没有自动帮你加黑加粗的选项。我取消之后，便找到了3款适合自己粗细、且风格和我相似的字体。到这，基本上大功告成了。接下来就是找一支特别黑的笔，因为激光打印机效果特别黑，正常五毛一支的晨光不太行。但听说高精度的喷墨打印机效果刚刚好，我试了低精度喷墨打印机，字体细节不太行。但身边没有高精度的做实验。

再点评一下经历，最难的是3的这一步，估计可以找到20多种貌似合适的字体，需要花费1个小时慢慢看。

**Comment by zhaoruheng** [comment]
非常感谢你的建议，已经将其纳入
